controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joints_positions:
      type: position_controllers/JointGroupPositionController

joints_positions:
  ros__parameters:
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
      - Joint5
      - Gripper
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
